import Foundation

// MARK: - String Table
// All UI strings used in the app, keyed for localization.
// Add new languages by inserting another language code alongside "en" and "ru".

enum Strings {
    static let table: [String: [String: String]] = [

        // MARK: Common actions
        "cancel":           ["en": "Cancel",            "ru": "Отмена"],
        "save":             ["en": "Save",              "ru": "Сохранить"],
        "done":             ["en": "Done",              "ru": "Готово"],
        "delete":           ["en": "Delete",            "ru": "Удалить"],
        "close":            ["en": "Close",             "ru": "Закрыть"],
        "clear":            ["en": "Clear",             "ru": "Очистить"],
        "clear_all":        ["en": "Clear All",         "ru": "Очистить всё"],
        "delete_all":       ["en": "Delete All",        "ru": "Удалить всё"],
        "remove":           ["en": "Remove",            "ru": "Удалить"],
        "edit":             ["en": "Edit",              "ru": "Редактировать"],
        "copy":             ["en": "Copy",              "ru": "Копировать"],
        "search":           ["en": "Search",            "ru": "Поиск"],
        "yes":              ["en": "Yes",               "ru": "Да"],
        "go":               ["en": "Go",                "ru": "Перейти"],
        "create":           ["en": "Create",            "ru": "Создать"],

        // MARK: Toolbar
        "toolbar.sidebar":              ["en": "Sidebar",       "ru": "Панель"],
        "toolbar.toggle_sidebar":       ["en": "Toggle Sidebar (⌘⇧S)", "ru": "Панель (⌘⇧S)"],
        "toolbar.inspector":            ["en": "Inspector",     "ru": "Инспектор"],
        "toolbar.toggle_inspector":     ["en": "Toggle Inspector (Strong's & Cross-Refs)", "ru": "Инспектор (Стронг и перекрёстные ссылки)"],
        "toolbar.search":               ["en": "Search",        "ru": "Поиск"],
        "toolbar.search_help":          ["en": "Search (⌘F)",   "ru": "Поиск (⌘F)"],

        // MARK: Sidebar tabs
        "tab.bookmarks":    ["en": "Bookmarks",         "ru": "Закладки"],
        "tab.notes":        ["en": "Notes",             "ru": "Заметки"],
        "tab.modules":      ["en": "Modules",           "ru": "Модули"],

        // MARK: Inspector tabs
        "tab.strongs":      ["en": "Strong's",          "ru": "Стронг"],
        "tab.crossrefs":    ["en": "Cross-Refs",        "ru": "Ссылки"],

        // MARK: Sidebar — modules
        "sidebar.no_translations":  ["en": "No Translations",  "ru": "Нет переводов"],
        "sidebar.manage":           ["en": "Manage...",         "ru": "Управление..."],
        "sidebar.settings_help":    ["en": "Settings",          "ru": "Настройки"],
        "sidebar.history_help":     ["en": "Reading History",   "ru": "История чтения"],

        // MARK: Inspector empty states
        "inspector.strongs_empty":      ["en": "Tap a verse to see Strong's numbers",                       "ru": "Нажмите на стих для просмотра номеров Стронга"],
        "inspector.strongs_title":      ["en": "Strong's Concordance",                                      "ru": "Симфония Стронга"],
        "inspector.crossref_empty":     ["en": "Right-click a verse and select Cross-References",           "ru": "Нажмите правой кнопкой на стих и выберите «Перекрёстные ссылки»"],
        "inspector.crossref_title":     ["en": "Cross-References",                                         "ru": "Перекрёстные ссылки"],

        // MARK: Drop overlay
        "drop.import_module":   ["en": "Drop to Import Module", "ru": "Перетащите для импорта модуля"],

        // MARK: Menu — Bible
        "menu.bible":                   ["en": "Bible",                     "ru": "Библия"],
        "menu.import_module":           ["en": "Import Module...",           "ru": "Импортировать модуль..."],
        "menu.manage_translations":     ["en": "Manage Translations",       "ru": "Управление переводами"],
        "menu.search":                  ["en": "Search...",                  "ru": "Поиск..."],
        "menu.add_pane":                ["en": "Add Translation Pane",       "ru": "Добавить панель перевода"],

        // MARK: Menu — View
        "menu.view":                    ["en": "View",                       "ru": "Вид"],
        "menu.bookmarks_sidebar":       ["en": "Bookmarks Sidebar",         "ru": "Панель закладок"],
        "menu.notes_sidebar":           ["en": "Notes Sidebar",             "ru": "Панель заметок"],
        "menu.modules_sidebar":         ["en": "Modules Sidebar",           "ru": "Панель модулей"],
        "menu.toggle_strongs":          ["en": "Toggle Strong's",           "ru": "Симфония Стронга"],
        "menu.toggle_crossrefs":        ["en": "Toggle Cross-References",   "ru": "Перекрёстные ссылки"],
        "menu.increase_font":           ["en": "Increase Font Size",        "ru": "Увеличить шрифт"],
        "menu.decrease_font":           ["en": "Decrease Font Size",        "ru": "Уменьшить шрифт"],
        "menu.reset_font":              ["en": "Reset Font Size",           "ru": "Сбросить размер шрифта"],

        // MARK: Menu — Bookmarks
        "menu.bookmarks":               ["en": "Bookmarks",                 "ru": "Закладки"],
        "menu.bookmark_verse":          ["en": "Bookmark Current Verse",    "ru": "Закладка на стих"],

        // MARK: Menu — Navigate
        "menu.navigate":                ["en": "Navigate",                  "ru": "Навигация"],
        "menu.prev_chapter":            ["en": "Previous Chapter",          "ru": "Предыдущая глава"],
        "menu.next_chapter":            ["en": "Next Chapter",              "ru": "Следующая глава"],
        "menu.prev_book":               ["en": "Previous Book",             "ru": "Предыдущая книга"],
        "menu.next_book":               ["en": "Next Book",                 "ru": "Следующая книга"],

        // MARK: Settings — Tabs
        "settings.tab.display":         ["en": "Display",       "ru": "Отображение"],
        "settings.tab.appearance":      ["en": "Appearance",    "ru": "Внешний вид"],
        "settings.tab.reading":         ["en": "Reading",       "ru": "Чтение"],
        "settings.tab.profiles":        ["en": "Profiles",      "ru": "Профили"],
        "settings.tab.general":         ["en": "General",       "ru": "Основные"],

        // MARK: Settings — Display
        "settings.font":                ["en": "Font",                          "ru": "Шрифт"],
        "settings.font_family":         ["en": "Family",                        "ru": "Гарнитура"],
        "settings.font_size":           ["en": "Size",                          "ru": "Размер"],
        "settings.font_size_pt":        ["en": "pt",                            "ru": "пт"],
        "settings.line_spacing":        ["en": "Line Spacing",                  "ru": "Межстрочный интервал"],
        "settings.word_spacing":        ["en": "Word Spacing",                  "ru": "Межсловный интервал"],
        "settings.layout":              ["en": "Layout",                        "ru": "Компоновка"],
        "settings.verse_numbers":       ["en": "Verse Numbers",                 "ru": "Номера стихов"],
        "settings.superscript":         ["en": "Superscript",                   "ru": "Надстрочный"],
        "settings.inline":              ["en": "Inline",                        "ru": "Встроенный"],
        "settings.margin":              ["en": "Margin",                        "ru": "На полях"],
        "settings.paragraph_mode":      ["en": "Paragraph Mode (no line breaks between verses)", "ru": "Режим абзацев (без разрывов строк между стихами)"],
        "settings.preview":             ["en": "Preview",                       "ru": "Предпросмотр"],
        "settings.reset_display":       ["en": "Reset Display to Defaults",     "ru": "Сбросить отображение"],

        // MARK: Settings — Appearance
        "settings.appearance":          ["en": "Appearance",                    "ru": "Вид"],
        "settings.theme":               ["en": "Theme",                         "ru": "Тема"],
        "settings.theme_auto":          ["en": "System Default",                "ru": "Системная"],
        "settings.theme_light":         ["en": "Light",                         "ru": "Светлая"],
        "settings.theme_dark":          ["en": "Dark",                          "ru": "Тёмная"],
        "settings.theme_sepia":         ["en": "Sepia",                         "ru": "Сепия"],
        "settings.colors":              ["en": "Colors",                        "ru": "Цвета"],
        "settings.accent_color":        ["en": "Accent Color",                  "ru": "Акцентный цвет"],
        "settings.highlight_intensity": ["en": "Verse Highlight Intensity",     "ru": "Яркость выделения стиха"],
        "settings.custom_colors":       ["en": "Custom Colors",                 "ru": "Пользовательские цвета"],
        "settings.text_color":          ["en": "Text Color",                    "ru": "Цвет текста"],
        "settings.background_color":    ["en": "Background Color",              "ru": "Цвет фона"],
        "settings.reset_colors":        ["en": "Reset Colors to Defaults",      "ru": "Сбросить цвета"],
        "settings.elements":            ["en": "Elements",                      "ru": "Элементы"],
        "settings.show_chapter_titles": ["en": "Show Chapter Titles",           "ru": "Показывать заголовки глав"],
        "settings.reset_appearance":    ["en": "Reset Appearance to Defaults",  "ru": "Сбросить внешний вид"],

        // MARK: Settings — Reading
        "settings.scroll_navigation":   ["en": "Scroll & Navigation",           "ru": "Прокрутка и навигация"],
        "settings.sync_scroll":         ["en": "Sync scroll across panes",      "ru": "Синхронная прокрутка панелей"],
        "settings.restore_position":    ["en": "Restore last reading position on launch", "ru": "Восстанавливать позицию чтения при запуске"],
        "settings.verse_display":       ["en": "Verse Display",                 "ru": "Отображение стихов"],
        "settings.verse_number_style":  ["en": "Verse Number Style",            "ru": "Стиль номеров стихов"],
        "settings.show_chapter_titles_reader": ["en": "Show chapter titles in reader", "ru": "Показывать заголовки глав в читалке"],

        // MARK: Settings — Profiles
        "settings.active_profile":      ["en": "Active Profile",                "ru": "Активный профиль"],
        "settings.profile":             ["en": "Profile",                       "ru": "Профиль"],
        "settings.profile_description": ["en": "Each profile has its own bookmarks, highlights, notes, and reading history.", "ru": "Каждый профиль имеет свои закладки, выделения, заметки и историю чтения."],
        "settings.manage_profiles":     ["en": "Manage Profiles",               "ru": "Управление профилями"],
        "settings.active":              ["en": "Active",                        "ru": "Активный"],
        "settings.delete_profile":      ["en": "Delete profile",                "ru": "Удалить профиль"],
        "settings.new_profile":         ["en": "New Profile",                   "ru": "Новый профиль"],
        "settings.delete_profile_title":["en": "Delete Profile",                "ru": "Удалить профиль"],
        "settings.profile_name":        ["en": "Profile name",                  "ru": "Название профиля"],
        "settings.profile_exists":      ["en": "A profile with this name already exists.", "ru": "Профиль с таким именем уже существует."],

        // MARK: Settings — General
        "settings.default_translation": ["en": "Default Translation",           "ru": "Перевод по умолчанию"],
        "settings.translation":         ["en": "Translation",                   "ru": "Перевод"],
        "settings.last_used":           ["en": "Last Used",                     "ru": "Последний использованный"],
        "settings.modules":             ["en": "Modules",                       "ru": "Модули"],
        "settings.module_directory":    ["en": "Module Directory",              "ru": "Папка модулей"],
        "settings.reveal_finder":       ["en": "Reveal in Finder",              "ru": "Показать в Finder"],
        "settings.import_module":       ["en": "Import Module...",              "ru": "Импортировать модуль..."],
        "settings.data_management":     ["en": "Data Management",               "ru": "Управление данными"],
        "settings.clear_history":       ["en": "Clear Reading History",         "ru": "Очистить историю чтения"],
        "settings.clear_history_desc":  ["en": "Remove all reading history entries", "ru": "Удалить все записи истории чтения"],
        "settings.clear_all_data":      ["en": "Clear All User Data",           "ru": "Очистить все данные"],
        "settings.clear_all_data_desc": ["en": "Remove all bookmarks, highlights, notes, and history for this profile", "ru": "Удалить все закладки, выделения, заметки и историю для этого профиля"],
        "settings.about":               ["en": "About",                         "ru": "О программе"],
        "settings.version":             ["en": "Version",                       "ru": "Версия"],
        "settings.build":               ["en": "Build",                         "ru": "Сборка"],
        "settings.language":            ["en": "Language",                      "ru": "Язык"],
        "settings.language_english":    ["en": "English",                       "ru": "Английский"],
        "settings.language_russian":    ["en": "Russian",                       "ru": "Русский"],

        // MARK: Settings — Alerts
        "alert.clear_history_title":    ["en": "Clear Reading History",         "ru": "Очистить историю чтения"],
        "alert.clear_history_msg":      ["en": "This will permanently delete all reading history. This cannot be undone.", "ru": "История чтения будет безвозвратно удалена. Это действие нельзя отменить."],
        "alert.clear_all_title":        ["en": "Clear All User Data",           "ru": "Очистить все данные"],
        "alert.clear_all_msg":          ["en": "This will permanently delete all bookmarks, highlights, notes, and reading history for the current profile. This cannot be undone.", "ru": "Все закладки, выделения, заметки и история чтения текущего профиля будут безвозвратно удалены. Это действие нельзя отменить."],

        // MARK: Bookmarks
        "bookmarks.title":              ["en": "Bookmarks",                     "ru": "Закладки"],
        "bookmarks.filter":             ["en": "Filter bookmarks...",           "ru": "Фильтр закладок..."],
        "bookmarks.show_flat":          ["en": "Show flat list",                "ru": "Плоский список"],
        "bookmarks.group_by_book":      ["en": "Group by book",                 "ru": "По книгам"],
        "bookmarks.sort_order":         ["en": "Sort order",                    "ru": "Порядок сортировки"],
        "bookmarks.delete_all_help":    ["en": "Delete all bookmarks",          "ru": "Удалить все закладки"],
        "bookmarks.delete_all_title":   ["en": "Delete All Bookmarks?",         "ru": "Удалить все закладки?"],
        "bookmarks.empty_title":        ["en": "No Bookmarks",                  "ru": "Нет закладок"],
        "bookmarks.empty_hint":         ["en": "Right-click a verse and select \"Bookmark Verse\" to save it here.", "ru": "Нажмите правой кнопкой на стих и выберите «Добавить закладку»."],
        "bookmarks.no_match":           ["en": "No matching bookmarks",         "ru": "Закладки не найдены"],
        "bookmarks.go_to_verse":        ["en": "Go to Verse",                   "ru": "Перейти к стиху"],
        "bookmarks.add_note":           ["en": "Add Note",                      "ru": "Добавить заметку"],
        "bookmarks.edit_note":          ["en": "Edit Note",                     "ru": "Редактировать заметку"],
        "bookmarks.remove_note":        ["en": "Remove Note",                   "ru": "Удалить заметку"],
        "bookmarks.remove":             ["en": "Remove Bookmark",               "ru": "Удалить закладку"],
        "bookmarks.delete_help":        ["en": "Delete bookmark",               "ru": "Удалить закладку"],
        "bookmarks.note_title":         ["en": "Bookmark Note",                 "ru": "Заметка к закладке"],

        // MARK: Notes
        "notes.title":                  ["en": "Notes",                         "ru": "Заметки"],
        "notes.filter":                 ["en": "Filter notes...",               "ru": "Фильтр заметок..."],
        "notes.show_flat":              ["en": "Show flat list",                "ru": "Плоский список"],
        "notes.group_by_book":          ["en": "Group by book",                 "ru": "По книгам"],
        "notes.sort_order":             ["en": "Sort order",                    "ru": "Порядок сортировки"],
        "notes.export_help":            ["en": "Export notes to text file",     "ru": "Экспорт заметок в текстовый файл"],
        "notes.delete_all_help":        ["en": "Delete all notes",              "ru": "Удалить все заметки"],
        "notes.delete_all_title":       ["en": "Delete All Notes?",             "ru": "Удалить все заметки?"],
        "notes.empty_title":            ["en": "No Notes",                      "ru": "Нет заметок"],
        "notes.empty_hint":             ["en": "Right-click a verse and select \"Add Note\" to save notes here.", "ru": "Нажмите правой кнопкой на стих и выберите «Добавить заметку»."],
        "notes.no_match":               ["en": "No matching notes",             "ru": "Заметки не найдены"],
        "notes.go_to_verse":            ["en": "Go to Verse",                   "ru": "Перейти к стиху"],
        "notes.edit":                   ["en": "Edit Note",                     "ru": "Редактировать заметку"],
        "notes.copy":                   ["en": "Copy Note",                     "ru": "Копировать заметку"],
        "notes.delete":                 ["en": "Delete Note",                   "ru": "Удалить заметку"],
        "notes.delete_help":            ["en": "Delete note",                   "ru": "Удалить заметку"],
        "notes.edit_title":             ["en": "Edit Note",                     "ru": "Редактировать заметку"],

        // MARK: History
        "history.title":                ["en": "Reading History",               "ru": "История чтения"],
        "history.clear_all":            ["en": "Clear All",                     "ru": "Очистить всё"],
        "history.empty_title":          ["en": "No Reading History",            "ru": "История чтения пуста"],
        "history.empty_hint":           ["en": "Your reading history will appear here as you navigate chapters.", "ru": "История чтения будет отображаться здесь по мере навигации по главам."],
        "history.today":                ["en": "Today",                         "ru": "Сегодня"],
        "history.yesterday":            ["en": "Yesterday",                     "ru": "Вчера"],

        // MARK: Search
        "search.placeholder":           ["en": "Search word or phrase...",      "ru": "Поиск слова или фразы..."],
        "search.go_to_verse_help":      ["en": "Go to verse reference",         "ru": "Перейти к ссылке на стих"],
        "search.close_help":            ["en": "Close search",                  "ru": "Закрыть поиск"],
        "search.go_to_ref_title":       ["en": "Go to Reference",               "ru": "Перейти к ссылке"],
        "search.ref_placeholder":       ["en": "e.g. John 3:16, Gen 1, Rev 21:1", "ru": "напр. Ин 3:16, Быт 1, Откр 21:1"],
        "search.ref_format":            ["en": "Book Chapter:Verse",            "ru": "Книга Глава:Стих"],
        "search.scope":                 ["en": "Search in",                     "ru": "Искать в"],
        "search.scope_all":             ["en": "All",                           "ru": "Всём"],
        "search.searching":             ["en": "Searching...",                  "ru": "Поиск..."],
        "search.no_results":            ["en": "No results found — try a different search term or scope", "ru": "Ничего не найдено — попробуйте другой запрос или область поиска"],
        "search.capped":                ["en": "(capped)",                      "ru": "(ограничено)"],
        "search.many_results":          ["en": "500+ results",                  "ru": "500+ результатов"],
        "search.sync_panes":            ["en": "Sync all panes to this verse",  "ru": "Синхронизировать все панели с этим стихом"],
        "search.open_parallel":         ["en": "Open in new parallel pane",     "ru": "Открыть в новой параллельной панели"],

        // MARK: Cross References
        "crossref.title":               ["en": "Cross References",              "ru": "Перекрёстные ссылки"],
        "crossref.back_help":           ["en": "Go back to previous verse",     "ru": "Вернуться к предыдущему стиху"],
        "crossref.close_help":          ["en": "Close cross-references panel",  "ru": "Закрыть панель перекрёстных ссылок"],
        "crossref.open_in_reader":      ["en": "Open in Reader",                "ru": "Открыть в читалке"],
        "crossref.verse_placeholder":   ["en": "Enter verse (e.g. John 3:16)",  "ru": "Введите стих (напр. Ин 3:16)"],
        "crossref.look_up":             ["en": "Look Up",                       "ru": "Найти"],
        "crossref.section":             ["en": "Cross References (TSK)",        "ru": "Перекрёстные ссылки (TSK)"],
        "crossref.loading":             ["en": "Loading cross-references...",   "ru": "Загрузка перекрёстных ссылок..."],
        "crossref.empty_title":         ["en": "Cross References",              "ru": "Перекрёстные ссылки"],
        "crossref.empty_hint":          ["en": "Enter a verse reference above, or tap a verse\nin the reader to see its cross-references.", "ru": "Введите ссылку на стих выше или нажмите на стих в читалке."],
        "crossref.none_found":          ["en": "No cross-references found",     "ru": "Перекрёстных ссылок не найдено"],
        "crossref.none_hint":           ["en": "This verse has no cross-references\nin the loaded modules.", "ru": "Для этого стиха нет перекрёстных ссылок\nв загруженных модулях."],

        // MARK: Strong's Sidebar
        "strongs.loading":              ["en": "Loading...",                    "ru": "Загрузка..."],
        "strongs.no_tags":              ["en": "No Strong's tags found for this verse.", "ru": "Теги Стронга для этого стиха не найдены."],
        "strongs.close_help":           ["en": "Close Strong's panel",          "ru": "Закрыть панель Стронга"],
        "strongs.transliteration":      ["en": "Transliteration",               "ru": "Транслитерация"],
        "strongs.pronunciation":        ["en": "Pronunciation",                 "ru": "Произношение"],
        "strongs.definition":           ["en": "Strong's Definition",           "ru": "Определение Стронга"],
        "strongs.kjv_usage":            ["en": "KJV Translation Usage",         "ru": "Использование в КЯВ"],
        "strongs.derivation":           ["en": "Derivation",                    "ru": "Происхождение"],
        "strongs.hebrew":               ["en": "Hebrew (Old Testament)",        "ru": "Еврейский (Ветхий Завет)"],
        "strongs.greek":                ["en": "Greek (New Testament)",         "ru": "Греческий (Новый Завет)"],
        "strongs.loading_similar":      ["en": "Loading similar entries...",    "ru": "Загрузка похожих записей..."],
        "strongs.no_similar":           ["en": "No similar entries found.",     "ru": "Похожие записи не найдены."],

        // MARK: Strong's Lookup
        "strongs_lookup.placeholder":   ["en": "Strong's number (H1234, G3056) or word...", "ru": "Номер Стронга (H1234, G3056) или слово..."],
        "strongs_lookup.hebrew":        ["en": "Hebrew (OT)",                   "ru": "Еврейский (ВЗ)"],
        "strongs_lookup.greek":         ["en": "Greek (NT)",                    "ru": "Греческий (НЗ)"],
        "strongs_lookup.all":           ["en": "All",                           "ru": "Все"],
        "strongs_lookup.searching":     ["en": "Searching...",                  "ru": "Поиск..."],
        "strongs_lookup.no_results":    ["en": "No results found",              "ru": "Ничего не найдено"],
        "strongs_lookup.try_hint":      ["en": "Try a Strong's number like H7225 or G3056", "ru": "Попробуйте номер Стронга, например H7225 или G3056"],
        "strongs_lookup.title":         ["en": "Strong's Concordance",          "ru": "Симфония Стронга"],
        "strongs_lookup.intro":         ["en": "Search by number (H1234) or word to look up Hebrew/Greek definitions.\nOr tap any verse in the Reader to see its Strong's tags.", "ru": "Введите номер (H1234) или слово для поиска еврейских/греческих определений.\nИли нажмите на любой стих в читалке, чтобы увидеть теги Стронга."],
        "strongs_lookup.select_entry":  ["en": "Select an entry",              "ru": "Выберите запись"],
        "strongs_lookup.nav_title":     ["en": "Strong's Concordance",          "ru": "Симфония Стронга"],

        // MARK: Import Module
        "import.importing":             ["en": "Importing...",                  "ru": "Импорт..."],
        "import.drop_hint":             ["en": "Drop .brbmod files here",       "ru": "Перетащите файлы .brbmod сюда"],
        "import.or_choose":             ["en": "or click \"Choose File\" to browse", "ru": "или нажмите «Выбрать файл» для просмотра"],
        "import.choose_file":           ["en": "Choose File...",                "ru": "Выбрать файл..."],

        // MARK: Manage Translations
        "manage.title":                 ["en": "Manage Translations",           "ru": "Управление переводами"],
        "manage.remove_confirm_title":  ["en": "Remove Translation?",           "ru": "Удалить перевод?"],
        "manage.installed":             ["en": "Installed",                     "ru": "Установлены"],
        "manage.assign_new_pane":       ["en": "Assign to New Pane",            "ru": "Назначить новой панели"],
        "manage.assign_pane":           ["en": "Assign to Pane",                "ru": "Назначить панели"],
        "manage.remove_ellipsis":       ["en": "Remove…",                       "ru": "Удалить…"],
        "manage.select_translation":    ["en": "Select a translation",          "ru": "Выберите перевод"],
        "manage.no_translations_title": ["en": "No Translations Installed",     "ru": "Переводы не установлены"],
        "manage.no_translations_hint":  ["en": "Import a .brbmod module to get started.", "ru": "Импортируйте модуль .brbmod для начала работы."],
        "manage.import_module":         ["en": "Import Module…",                "ru": "Импортировать модуль…"],
        "manage.add_pane_help":         ["en": "Add reader pane",               "ru": "Добавить панель читалки"],
        "manage.remove_pane_help":      ["en": "Remove last pane",              "ru": "Убрать последнюю панель"],
        "manage.language":              ["en": "Language",                      "ru": "Язык"],
        "manage.versification":         ["en": "Versification",                 "ru": "Нумерация стихов"],
        "manage.format":                ["en": "Format",                        "ru": "Формат"],
        "manage.tagged":                ["en": "Tagged (Strong's)",             "ru": "С тегами (Стронг)"],
        "manage.plain_text":            ["en": "Plain text",                    "ru": "Обычный текст"],
        "manage.books":                 ["en": "Books",                         "ru": "Книг"],
        "manage.verses":                ["en": "Verses",                        "ru": "Стихов"],
        "manage.file_size":             ["en": "File size",                     "ru": "Размер файла"],
        "manage.strongs":               ["en": "Strong's",                      "ru": "Стронг"],
        "manage.crossrefs":             ["en": "Cross-refs",                    "ru": "Перекрёстные ссылки"],
        "manage.copyright":             ["en": "Copyright",                     "ru": "Авторские права"],
        "manage.notes_field":           ["en": "Notes",                         "ru": "Примечания"],
        "manage.pane_assignment":       ["en": "Pane Assignment",               "ru": "Назначение панели"],
        "manage.pane_label":            ["en": "Pane",                          "ru": "Панель"],

        // MARK: Reader
        "reader.select_translation":    ["en": "Select translation",            "ru": "Выбрать перевод"],
        "reader.select_book":           ["en": "Select book",                   "ru": "Выбрать книгу"],
        "reader.select_chapter":        ["en": "Select chapter",                "ru": "Выбрать главу"],
        "reader.prev_chapter":          ["en": "Previous chapter",              "ru": "Предыдущая глава"],
        "reader.next_chapter":          ["en": "Next chapter",                  "ru": "Следующая глава"],
        "reader.split_horizontal":      ["en": "Split horizontally",            "ru": "Разделить горизонтально"],
        "reader.split_vertical":        ["en": "Split vertically",              "ru": "Разделить вертикально"],
        "reader.close_pane":            ["en": "Close pane",                    "ru": "Закрыть панель"],
        "reader.bookmark_verse":        ["en": "Bookmark this verse",           "ru": "Добавить закладку на стих"],
        "reader.remove_bookmark":       ["en": "Remove bookmark",               "ru": "Удалить закладку"],
        "reader.highlight_verse":       ["en": "Highlight verse",               "ru": "Выделить стих"],
        "reader.add_note":              ["en": "Add note",                      "ru": "Добавить заметку"],
        "reader.edit_note":             ["en": "Edit note",                     "ru": "Редактировать заметку"],
        "reader.no_translations":       ["en": "No translations loaded.\nImport a .brbmod module to get started.", "ru": "Переводы не загружены.\nИмпортируйте модуль .brbmod для начала работы."],
        "reader.loading":               ["en": "Loading...",                    "ru": "Загрузка..."],

        // MARK: Bible book names
        "book.genesis":             ["en": "Genesis",           "ru": "Бытие"],
        "book.exodus":              ["en": "Exodus",            "ru": "Исход"],
        "book.leviticus":           ["en": "Leviticus",         "ru": "Левит"],
        "book.numbers":             ["en": "Numbers",           "ru": "Числа"],
        "book.deuteronomy":         ["en": "Deuteronomy",       "ru": "Второзаконие"],
        "book.joshua":              ["en": "Joshua",            "ru": "Иисус Навин"],
        "book.judges":              ["en": "Judges",            "ru": "Судей"],
        "book.ruth":                ["en": "Ruth",              "ru": "Руфь"],
        "book.1_samuel":            ["en": "1 Samuel",          "ru": "1 Царств"],
        "book.2_samuel":            ["en": "2 Samuel",          "ru": "2 Царств"],
        "book.1_kings":             ["en": "1 Kings",           "ru": "3 Царств"],
        "book.2_kings":             ["en": "2 Kings",           "ru": "4 Царств"],
        "book.1_chronicles":        ["en": "1 Chronicles",      "ru": "1 Паралипоменон"],
        "book.2_chronicles":        ["en": "2 Chronicles",      "ru": "2 Паралипоменон"],
        "book.ezra":                ["en": "Ezra",              "ru": "Ездра"],
        "book.nehemiah":            ["en": "Nehemiah",          "ru": "Неемия"],
        "book.esther":              ["en": "Esther",            "ru": "Есфирь"],
        "book.job":                 ["en": "Job",               "ru": "Иов"],
        "book.psalms":              ["en": "Psalms",            "ru": "Псалтирь"],
        "book.proverbs":            ["en": "Proverbs",          "ru": "Притчи"],
        "book.ecclesiastes":        ["en": "Ecclesiastes",      "ru": "Екклесиаст"],
        "book.song_of_solomon":     ["en": "Song of Solomon",   "ru": "Песня Песней"],
        "book.isaiah":              ["en": "Isaiah",            "ru": "Исаия"],
        "book.jeremiah":            ["en": "Jeremiah",          "ru": "Иеремия"],
        "book.lamentations":        ["en": "Lamentations",      "ru": "Плач Иеремии"],
        "book.ezekiel":             ["en": "Ezekiel",           "ru": "Иезекииль"],
        "book.daniel":              ["en": "Daniel",            "ru": "Даниил"],
        "book.hosea":               ["en": "Hosea",             "ru": "Осия"],
        "book.joel":                ["en": "Joel",              "ru": "Иоиль"],
        "book.amos":                ["en": "Amos",              "ru": "Амос"],
        "book.obadiah":             ["en": "Obadiah",           "ru": "Авдий"],
        "book.jonah":               ["en": "Jonah",             "ru": "Иона"],
        "book.micah":               ["en": "Micah",             "ru": "Михей"],
        "book.nahum":               ["en": "Nahum",             "ru": "Наум"],
        "book.habakkuk":            ["en": "Habakkuk",          "ru": "Аввакум"],
        "book.zephaniah":           ["en": "Zephaniah",         "ru": "Софония"],
        "book.haggai":              ["en": "Haggai",            "ru": "Аггей"],
        "book.zechariah":           ["en": "Zechariah",         "ru": "Захария"],
        "book.malachi":             ["en": "Malachi",           "ru": "Малахия"],
        "book.matthew":             ["en": "Matthew",           "ru": "Матфей"],
        "book.mark":                ["en": "Mark",              "ru": "Марк"],
        "book.luke":                ["en": "Luke",              "ru": "Лука"],
        "book.john":                ["en": "John",              "ru": "Иоанн"],
        "book.acts":                ["en": "Acts",              "ru": "Деяния"],
        "book.romans":              ["en": "Romans",            "ru": "Римлянам"],
        "book.1_corinthians":       ["en": "1 Corinthians",     "ru": "1 Коринфянам"],
        "book.2_corinthians":       ["en": "2 Corinthians",     "ru": "2 Коринфянам"],
        "book.galatians":           ["en": "Galatians",         "ru": "Галатам"],
        "book.ephesians":           ["en": "Ephesians",         "ru": "Ефесянам"],
        "book.philippians":         ["en": "Philippians",       "ru": "Филиппийцам"],
        "book.colossians":          ["en": "Colossians",        "ru": "Колоссянам"],
        "book.1_thessalonians":     ["en": "1 Thessalonians",   "ru": "1 Фессалоникийцам"],
        "book.2_thessalonians":     ["en": "2 Thessalonians",   "ru": "2 Фессалоникийцам"],
        "book.1_timothy":           ["en": "1 Timothy",         "ru": "1 Тимофею"],
        "book.2_timothy":           ["en": "2 Timothy",         "ru": "2 Тимофею"],
        "book.titus":               ["en": "Titus",             "ru": "Титу"],
        "book.philemon":            ["en": "Philemon",          "ru": "Филимону"],
        "book.hebrews":             ["en": "Hebrews",           "ru": "Евреям"],
        "book.james":               ["en": "James",             "ru": "Иаков"],
        "book.1_peter":             ["en": "1 Peter",           "ru": "1 Петра"],
        "book.2_peter":             ["en": "2 Peter",           "ru": "2 Петра"],
        "book.1_john":              ["en": "1 John",            "ru": "1 Иоанна"],
        "book.2_john":              ["en": "2 John",            "ru": "2 Иоанна"],
        "book.3_john":              ["en": "3 John",            "ru": "3 Иоанна"],
        "book.jude":                ["en": "Jude",              "ru": "Иуда"],
        "book.revelation":          ["en": "Revelation",        "ru": "Откровение"],
    ]
}
